CREATE TABLE IF NOT EXISTS content (
    id BIGSERIAL PRIMARY KEY NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    name VARCHAR NOT NULL,
    description VARCHAR,
    content_type VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS tag (
    id BIGSERIAL PRIMARY KEY NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    name VARCHAR UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS content_tags (
    id BIGSERIAL PRIMARY KEY NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    content_id BIGSERIAL NOT NULL,
    tag_id BIGSERIAL NOT NULL REFERENCES tag(id)
);